// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zddkgdxjfxheqsmfrewe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkZGtnZHhqZnhoZXFzbWZyZXdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzODY5MDMsImV4cCI6MjA4ODk2MjkwM30.JWzLE6cUnjYY7VGMIJFbpd5RH5vU0wgeTOJR6-rohdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});